### ISSUE TITLE
Queue Component with Horizon

### ISSUE THREAD

**Issue by vbotingnon** [mattstauffer/Torch#104]
Is an example possible by creating a queue for use by Horizon?

**Comment by diego-vieira** [comment]
Have you tried to follow the installation steps for Horizon onto your app?

https://laravel.com/docs/5.5/horizon

**Comment by vbotingnon** [comment]
I want this project to queue up another project with Laravel / Horizon read and process.

Doing as per his example, he generates the redis queue in a format that Horizon does not recognize.

Installing horizon in the external project will it record in the correct format? I even tried it unsuccessfully. Do you believe it possible?

**Comment by diego-vieira** [comment]
I see what you mean now.

I think that normally you would have Horizon run the app code that queued the job.

I'm sure you can make it work, but it really depends on how much effort you want to put into it. Just thinking that it's going to be a big job.

**Comment by vbotingnon** [comment]
Exactly, I will think of another option. Thank you
