### ISSUE TITLE
Plans for Upgrade to 7.0

### ISSUE THREAD

**Issue by jamespavett** [mattstauffer/Torch#144]
Hi,

Are there any plans for an upgrade to 7.0?

Following the process for Routing, I have been able to set everything up working with 6.0 just fine. However when I used 7.0, the only error I see to have it when I pass a redirect to the UrlGenerator:

```
$router->redirect('/', '/menu');

// Create the redirect instance
$redirect = new Redirector(new UrlGenerator($router->getRoutes(), $request));
```

![image](https://user-images.githubusercontent.com/10764464/82572076-c9f85800-9b7b-11ea-9ef3-728a59955e0f.png)

Any thoughts would be greatly appreciated.

**Comment by StephaneBour** [comment]
Hello @jamespavett ,

For named routes, you need to declare the need before the method, like this :

```php
$router->name('home')->get('/', function () {
    return 'hello world!';
});
```
