### ISSUE TITLE
Router

### ISSUE THREAD

**Issue by Intrflex** [mattstauffer/Torch#146]
Is there any way of making the Router static so I can call Route::get, Route::resource etc?

**Comment by StephaneBour** [comment]
Hello,

It's not possible to use the facades without Laravel. Dependencies are important, and facades need a Laravel app.

In theory, it is possible to reproduce this behavior, with a singleton class which stores the router, and a "facade" class which takes the facade class of Laravel.

```php
public static function __callStatic($method, $args)
    {
        $instance = RouterSingleton::get();

        if (! $instance) {
            throw new RuntimeException('A facade root has not been set.');
        }

        return $instance->$method(...$args);
    }
```

**Comment by Intrflex** [comment]
Okay brilliant also one more question, I've enabled the middleware components but no matter what I don't seem to be able to access the Request dependency injection , in either the Router or any controllers set it to use "Illuminate\Http\Request;" and followed exactly what it said in the index.php on middleware
