### ISSUE TITLE
Queue

### ISSUE THREAD

**Issue by Intrflex** [mattstauffer/Torch#150]
Is there any way of making this work with the database driver?

**Comment by Gummibeer** [comment]
As the Database and Queue components work standalone they should also work together.
But I highly recommend to don't use the database driver as table-locks don't play well with the queue table.
We had it very often, without and immense load, that jobs have been processed twice (multiple queue worker) or never got to the queue as the dispatch failed.

**Comment by Gummibeer** [comment]
duplicates #103 
@mattstauffer can be closed in favor of the other issue.
