### ISSUE TITLE
Bring back Whoops

### ISSUE THREAD

**Issue by mattstauffer** [mattstauffer/Torch#151]
In testing the latest updates I discovered that error handling isn't working *at all*.

If we make this change to all of the components:

https://github.com/mattstauffer/Torch/commit/06db57726c2d8412719e23cb7d2727f929c04d5b

We'll at least get *some* error handling back. But I'd love for someone to dig into why Whoops isn't working.

**Comment by nathane** [comment]
@mattstauffer you may need to enable whoops by passing `'debug' => true`
```PHP
$app = new App([
    'settings' => [
    	 // Enable whoops
        'debug' => true,

        // Support click to open editor
        'whoops.editor' => 'sublime',

        // Set page title
        'whoops.page_title' => 'Custom page title',

        // Display call stack in orignal slim error when debug is off
        'displayErrorDetails' => true,
    ]
]);
```
> https://github.com/zeuxisoo/php-slim-whoops/tree/0.6.x#options
