### ISSUE TITLE
question about writing this package

### ISSUE THREAD

**Issue by Stevemoretz** [mattstauffer/Torch#186]
Hi I'm curious to know, did you figure this out all by yourself?
That how all these things work in Laravel, then wrote these?
Or is there an official tutorial somewhere and these are the examples based on that?

**Comment by mattstauffer** [comment]
I figured most of this out myself, yep. There was a guy named Tree.. something.. crap, I can't remember his handle now.. in the EARLIEST days who gave me a leg up figuring out how to bootstrap the application container, so I owe him huge! But other than that, yes, I figured it all by source diving and trial and error.

**Comment by Stevemoretz** [comment]
Wow thanks Matt this is impressive!

**Comment by mattstauffer** [comment]
Thanks so much Steve! :)
