### ISSUE TITLE
Great Repo! Any plans for more?

### ISSUE THREAD

**Issue by drakakisgeo** [mattstauffer/Torch#189]
Hi Matt, I was really glad to find this repo. Any plans to include any of those packages "illuminate/testing" , "illuminate/mail" in the future ? Struggling to find the way to do it in an old Slim API.

In the meantime if I figure it out those myself, I will definitely make a PR, since this is really really useful for legacy apps.

Again, thanks for your openness .

**Comment by mattstauffer** [comment]
Glad you like it! I don't have time nor energy to add any of those right now, but they'd be welcome pull requests from you or anyone else. Thanks!
