### ISSUE TITLE
Blade?

### ISSUE THREAD

**Issue by TuckerWhitehouse** [mattstauffer/Torch#21]

**Comment by mattstauffer** [comment]
What's your question?

**Comment by TuckerWhitehouse** [comment]
I didn't see it on the roadmap or in the 4.2 branch so I wasn't sure whether it was something you were looking to include in this project, or had intentionally left out.

**Comment by mattstauffer** [comment]
Ah, sure--yah, anything having to do with the view system, Blade, the
rendering engines, etc. would be great--thanks!

**Comment by mattstauffer** [comment]
Added to roadmap. https://github.com/mattstauffer/Torch/commit/1b60dcb0a6f224e60798b34c6a25bdb75e233e64
