### ISSUE TITLE
How to use DB::raw?

### ISSUE THREAD

**Issue by dead23angel** [mattstauffer/Torch#28]
In the documentation http://laravel.com/docs/5.1/queries#selects, there is a section **Raw Expressions**
which is an example of code to use raw expressions
```
$users = DB::table('users')
                     ->select(DB::raw('count(*) as user_count, status'))
                     ->where('status', '<>', 1)
                     ->groupBy('status')
                     ->get();
```
And how it can be used without a framework?

**Comment by mattstauffer** [comment]
@dead23angel what have you tried so far?

**Comment by dead23angel** [comment]
I tried to load facade Illuminate\Support\Facades\DB.
Once an error occurs, you can not find a class db, studying sources laravel realized that the class is an alias db class Illuminate\Database\DatabaseManager this class is to declare the already failed.
In its constructor is necessary to pass an instance of the container and ConnectionFactory

Sory my bad english

**Comment by mattstauffer** [comment]
@dead23angel Did you start by using Torch's example of how to set up the database?

https://github.com/mattstauffer/Torch/tree/master/components/database

**Comment by dead23angel** [comment]
Yes. I used your example, for the use of the components of the framework without laravel. All that is connected to the database works, except DB::raw, I can not seem to understand

**Comment by dead23angel** [comment]
Probably will not use raw expression?
Something so none and did not answer me.

**Comment by vlakoff** [comment]
You can do `Capsule::raw()` or `use Illuminate\Database\Capsule\Manager as DB;`

**Comment by dead23angel** [comment]
@vlakoff Thanks!
I tested a little way, and this has not worked. Now everything fell into place.
