### ISSUE TITLE
View / Template Example

### ISSUE THREAD

**Issue by kayyyy** [mattstauffer/Torch#31]
Hey @mattstauffer 

awesome collection, really thanks for this.
Currently i am struggling to get a working view/template engine.
I tried it with twig but i run into several errors.

Do you have maybe a good example for twig or blade / how to use this in a legacy app?

**Comment by mattstauffer** [comment]
@kayyyy just got merged: 
https://github.com/mattstauffer/Torch/tree/master/components/view
