### ISSUE TITLE
Eloquent and softDeletes

### ISSUE THREAD

**Issue by huglester** [mattstauffer/Torch#33]
Hello,

Eloquent works for me in 5.1, but when I change composer.json to use 5.2 tree, I get :
```php
BadMethodCallException: Call to undefined method Illuminate\Database\Query\Builder::onlyTrashed()
```

Any idea what could be wrong?

**Comment by mattstauffer** [comment]
@huglester not sure. still running into this issue?

**Comment by huglester** [comment]
I will check when I get home

**Comment by huglester** [comment]
I can't reproduce now. Will re-open if needed! thanks
