### ISSUE TITLE
Split out separate README files for each component

### ISSUE THREAD

**Issue by mattstauffer** [mattstauffer/Torch#40]
So that it's less confusing when someone goes to an individual component's folder in GitHub and doesn't know where to go.

(Originally suggested by @philsturgeon)

**Comment by Rubemlrm** [comment]
Can we Still help provide a readme information for each file? Or the ideia was dropped?

**Comment by mattstauffer** [comment]
@Rubemlrm It's still an open issue, so that means it's still up for grabs. :)

**Comment by Rubemlrm** [comment]
@mattstauffer nice nice . i will submit a README.MD example for one of the component. if this match with the information you need i will provide a readme.md to the other components too. what do you think about this idea ?

**Comment by mattstauffer** [comment]
Closed via #57
