### ISSUE TITLE
Scheduler component?

### ISSUE THREAD

**Issue by drjoju** [mattstauffer/Torch#41]
Hello,

What about a Task Scheduling component? As I see the task scheduling is in the Kernel of Laravel (ConsoleKernel). Needs the task scheduling component being so tied to the core?

Best regards

**Comment by mattstauffer** [comment]
I think it's not a separatable component, but I've never tried. If someone feels up for it it'd be welcome!

**Comment by Gummibeer** [comment]
I'm checking it right now - first look: requires some more illuminate packages but should work without the Laravel foundation. But will see how it works.^^

**Comment by Gummibeer** [comment]
Okay, was easier than thought but still not really easy.^^
It's also questionable how useful it is - but as there's also a component for the queue and other deep Laravel stuff - here it is. 😉
