### ISSUE TITLE
how to get config value from multiple config file at a time

### ISSUE THREAD

**Issue by ngangchill** [mattstauffer/Torch#42]
I dont want to get config value from different file by creating multiple instance of illuminate \config.

// Init
## For database :
     $config = new Repository(require $configPath . 'Db.php');
     // Get config using the get method

## for Cache:

// Init
      $CacheConfig = new Repository(require $configPath . 'cache.php');
    

How can i get config value from multiple file  just in $config array

and how to add them to container to use with laravel components blade or cache as configuration

**Comment by dead23angel** [comment]
Hi @ngangchill !

```php
$array = [
    'app' => require $configPath . 'app.php',
    'cache' => require $configPath . 'cache.php',
    'db' => require $configPath . 'database.php'
];

$config = new Repository($array);
```

file config/app.php
```php
<?php

return [
    'siteName' => 'Torch Config',
    'user' => 'Slim'
];
```

file config/cache.php
```php
<?php

return [
    'driver' => 'test'
];

```

file config/database.php
```php
<?php

return [
    'name' => 'test',
    'user' => 'user'
];

```

use
```php
$config->get('app.siteName');
$config['app.user'];
$config->get('cache.driver');
$config->get('db.name');
```

**Comment by ngangchill** [comment]
thanks for your replay..



How can i pass these config values to laravel container for using with laravel/cache,laravel/view as configuration @dead23angel 
e.g 
$container = new Container;
    $container['config'] = [
        'cache.default' => 'redis',
        'cache.stores.redis' => [
            'driver' => 'redis',
            'connection' => 'default'
        ],
        'cache.prefix' => 'illuminate_non_laravel',
        'database.redis' => [
            'cluster' => false,
            'default' => [
                'host' => '127.0.0.1',
                'port' => 6379,
                'database' => 0,
            ],
        ]
    ];

**Comment by dead23angel** [comment]
Hi @ngangchill !
```php
$array = [
    'app' => require $configPath . 'app.php',
    'cache' => require $configPath . 'cache.php',
    'db' => require $configPath . 'database.php'
];

$config = new Repository($array);
$container = new Illuminate\Container\Container;

$container->instance('config', $config);
```

It should work, but I have not tested.

**Comment by ngangchill** [comment]
many many thanx @dead23angel 
 i used it like: 
$array = [
    'app' => require $configPath . 'app.php',
    'cache' => require $configPath . 'cache.php',
    'db' => require $configPath . 'database.php'
];

$config = new Repository($array);
$container = new Illuminate\Container\Container;

$container['config'] = $config;


& it works fine..

thanx
