### ISSUE TITLE
Routing - Redirecting

### ISSUE THREAD

**Issue by Riversedgedesigns** [mattstauffer/Torch#45]
In Laravel redirecting in your controller was a huge time saver. Your code example does not include this feature. Exploring the vendor code it looks like redirecting is included in the package. The question is how to do that?

Laravel command for redirecting:
return redirect()->route('products.index');

After playing around a bit with your code im completely lost on how to go about using the redirect feature.
Is this possible with your code?

**Comment by dead23angel** [comment]
redirect helper function is in the Illuminate/foundation, this package is no longer available for installation. So to create this function, you have to yourself.

Or you can try to use a Redirector class like this:

```php
use Illuminate\Routing\Redirector;
use Illuminate\Routing\UrlGenerator;

$redirect = new Redirector(new UrlGenerator);
```

use
```php
return $redirect->home();
return $redirect->back();
return $redirect->to('/');
```


Forgive me for my bad english

**Comment by Riversedgedesigns** [comment]
That worked thanks!
