### ISSUE TITLE
Routing component, implement middleware

### ISSUE THREAD

**Issue by ptraceur** [mattstauffer/Torch#46]
Hi,

first of all let me congratulate your for your amazing work. I'm currently experimenting things, and I'm focusing essentially on the Routing component. I currently have a micro app with the router implemented with some Controllers. 

My question is, is it complicated to implement middlewares? What should I do to make this possible? Could you point me in the right direction please?

Thanks :+1:

**Comment by dead23angel** [comment]
Hi, @ptraceur !
```php
<?php

require_once 'vendor/autoload.php';
use Illuminate\Container\Container;
use Illuminate\Events\Dispatcher;
use Illuminate\Http\Request;
use Illuminate\Routing\Router;

$events = new Dispatcher(new Container);

$router = new Router($events);

$routeMiddleware = [
     'auth' => \App\Http\Middleware\Authenticate::class,
    'auth.basic' => \Illuminate\Auth\Middleware\AuthenticateWithBasicAuth::class,
    'guest' => \App\Http\Middleware\RedirectIfAuthenticated::class,
];

foreach ($routeMiddleware as $key => $middleware) {
    $router->middleware($key, $middleware);
}

require_once 'routes.php';

$request = Request::capture();

$response = $router->dispatch($request);

$response->send();
```

route.php
```php
<?php
use Illuminate\Routing\Router;
/** @var $router Router */
$router->get('/', function () {
    return 'hello world!';
});
$router->get('bye', function () {
    return 'goodbye world!';
});
$router->group(['namespace' => 'App\Controllers', 'prefix' => 'users', 'middleware' => 'auth'], function (Router $router) {
    $router->get('/', ['name' => 'users.index', 'uses' => 'UsersController@index']);
    $router->post('/', ['name' => 'users.store', 'uses' => 'UsersController@store']);
});

$router->any('{any}', function () {
    return 'four oh four';
})->where('any', '(.*)');
```

Must make, but I have not tested.

**Comment by ptraceur** [comment]
Well that worked as expected. I've added a folder `Middlewares` and added to composer autoload, then created a middleware with its normal structure as in [Laravel docs](https://laravel.com/docs/5.1/middleware) and following yours approach it all worked as expected. Thanks @dead23angel. 

Another thing, redirect helper `return redirect('home')` seems it isn't working for some reason, although I have a route named home. I got this error in the error log file:

```
PHP Fatal error:  Uncaught Error: Call to undefined function Middlewares\redirect()
```

I have these packages installed in the vendor directory:

```json
"require": {
	"illuminate/routing": "~5.1.16",
	"illuminate/events": "~5.1.16",
	"illuminate/config": "~5.1.0",
	"larapack/dd": "^1.0",
	"filp/whoops": "^2.1",
	"illuminate/database": "^5.1"
}
```

I'm probably missing some laravel package to make the redirect possible to use, any idea what could that be?

Thanks again

**Comment by dead23angel** [comment]
@ptraceur How to use redirects I wrote here https://github.com/mattstauffer/Torch/issues/45

**Comment by ptraceur** [comment]
Cool @dead23angel.

Thanks for your time, have a nice day 😄

**Comment by mattstauffer** [comment]
@dead23angel I'd love if you were up for PRing some advanced routing sections to the Torch code itself so we could show examples for how to do redirects and middleware in the code itself--maybe as a sub-section of the routing section or in a separate section.

No worries if you're not interested, but I figured I'd throw it out there as an idea.
