### ISSUE TITLE
Http component

### ISSUE THREAD

**Issue by sobhan93** [mattstauffer/Torch#71]
How can we setup and use the Http component in these standalone packages?

https://github.com/illuminate/http

**Comment by Rubemlrm** [comment]
i think that we can try por that.

**Comment by sobhan93** [comment]
I could not.
Can you give me a sample?

**Comment by coccoinomane** [comment]
Hi! This is particularly relevant since Zttp is not updated anymore :-(

**Comment by Gummibeer** [comment]
I will try my best to add this. I will let you know at the end of the weekend how far I got. 😂

**Comment by Gummibeer** [comment]
that's solved by #175

**Comment by mattstauffer** [comment]
Thanks @Gummibeer!

**Comment by coccoinomane** [comment]
It works great!
Thank you @Gummibeer  😍

**Comment by Gummibeer** [comment]
@coccoinomane no problem. Glad it helps! 🙂
