### ISSUE TITLE
Finish updating all components to 5.5

### ISSUE THREAD

**Issue by mattstauffer** [mattstauffer/Torch#73]
You can see the current list in the README but I'm encapsulating this here for the purpose of asking for help.

Here's what it takes to "move a component over": 

0. Find the correct Issue (see those linked in the comments below) for the given component. Leave a comment in that issue showing you'll be pulling this task.
1. Grab the code for that component from the older branch and put it into the appropriate folder in the newer branch. Or, more likely, it's sitting in the newer branch, just still with the old code and Composer dependencies. Just update it in place.
2. Update the `composer.json` references to Laravel `"~5.5.0"`
3. Try to `composer install`; see if anything breaks and whether you also need to update the versions of any other dependencies, or add or remove any others
4. Once `composer install` works, spin up the PHP server (`php -S localhost:8080`) and then visit each route that's defined in that component's `index.php` (e.g. `http://localhost:8080/` for the root of the component you're testing) and test whether everything works as expected
5. If it all works, PR it! If you get stuck, PR where you are with notes about what got stuck.

Need to move from the Laravel 5.1 branch:

- [x] [Container](https://github.com/mattstauffer/Torch/tree/5.1/components/container)
- [x] [Database](https://github.com/mattstauffer/Torch/tree/5.1/components/database)
- [x] [Pagination](https://github.com/mattstauffer/Torch/tree/5.1/components/pagination)
- [x] [Middleware](https://github.com/mattstauffer/Torch/tree/5.1/components/middleware)

Need to be finished moving from the Laravel 4.2 branch (imported but needs to be tested and tweaked):

- [ ] [Mail](https://github.com/mattstauffer/Torch/tree/master/4.2/mail)
- [x] [Queue](https://github.com/mattstauffer/Torch/tree/master/4.2/queue)

**Comment by Rubemlrm** [comment]
I think maybe this weekend or next monday i can try port the database and container to 5.5, so we can try speed up this migration =)

**Comment by jonathanbossenger** [comment]
@mattstauffer would it make sense to list all component moves as their own, separate issue, then folks can own one component at a time? Happy to also help with creating said issues.

**Comment by mattstauffer** [comment]
@jonathanbossenger sure! as long as we namespace them in a way that makes it clear they're all related to this one. Thank you!

**Comment by jonathanbossenger** [comment]
How does this sound

`Component updates for Laravel 5.5 : {Component title}`

And then reference this in the ticket description

**Comment by mattstauffer** [comment]
Great! Thanks!!

Sent from Outlook<https://aka.ms/qtex0l> for iOS
________________________________

**Comment by jonathanbossenger** [comment]
Sample issue created #74 let me know if you think we need anything else, otherwise I'll create the rest of the issues.

**Comment by mattstauffer** [comment]
@jonathanbossenger Perfect--thank you!

**Comment by shalvah** [comment]
@mattstauffer Why don't we go all the way to 5.6?

**Comment by mattstauffer** [comment]
@shalvah I like to complete each version we've started before upgrading; but also, it's LTS. :) But once we finish 5.5 I'll probably have us do 5.6 and then 5.7.

**Comment by jonathanbossenger** [comment]
I've created the separate issues for each component. May I suggest that component specific discussion and PR's happen against these tickets?

Personally I'm going to attempt the Container component over the course of this weekend/the coming week.

**Comment by diego-vieira** [comment]
@mattstauffer Laravel 6.0 is now LTS. Are we ready to starting migrating the components over or do we need to complete the migration from 4.2 > 5.1 > 5.5 for the pending components?

Happy to send a PR.

**Comment by mattstauffer** [comment]
@diego-vieira I think we can start picking up the 6.0 migrations. I'll make the issue for it. Thanks!

**Comment by mattstauffer** [comment]
@diego-vieira done: https://github.com/mattstauffer/Torch/issues/106
