### ISSUE TITLE
Component updates for Laravel 5.5 : Container

### ISSUE THREAD

**Issue by jonathanbossenger** [mattstauffer/Torch#74]
Update the [Container](https://github.com/mattstauffer/Torch/tree/5.1/components/container) Component to Laravel 5.5 

See #73 for full details of this task/requirements.

**Comment by jonathanbossenger** [comment]
I'm going to work on tackling this this coming weekend/week.

**Comment by cyberEst1919** [comment]
this issue is also done i guess?
https://github.com/mattstauffer/Torch/tree/master/components/container

**Comment by mattstauffer** [comment]
@cyberEst1919 nope, the container is on 5.1.

https://github.com/mattstauffer/Torch/blob/master/components/container/composer.json#L6
