### ISSUE TITLE
Component updates for Laravel 5.5 : Database

### ISSUE THREAD

**Issue by jonathanbossenger** [mattstauffer/Torch#79]
Update the [Database](https://github.com/mattstauffer/Torch/tree/5.1/components/database) Component to Laravel 5.5 

See #73 for full details of this task/requirements.

**Comment by cyberEst1919** [comment]
i guess this issue can be closed?
seems that 5.5 database already done, or is there something missing?https://github.com/mattstauffer/Torch/tree/master/components/database

**Comment by mattstauffer** [comment]
Thanks @cyberEst1919!
