### ISSUE TITLE
Queue artisan:listen

### ISSUE THREAD

**Issue by cansozeri** [mattstauffer/Torch#8]
Hi,

 I have attached and working with sync driver in my project, but what if we want to work with beanstalkd driver ??

How can I run artisan command outside Laravel ??

I have to use artisan:listen, I think it need for driver iron.io too or amazon ??

I culdn't figure it out to use the artisan:listen from outside of Laravel .. 

Regards,

**Comment by mattstauffer** [comment]
@cansozeri we don't have an artisan component up yet. It's in progress here: https://github.com/mattstauffer/Torch/pull/22

**Comment by Stevemoretz** [comment]
What about now?
