### ISSUE TITLE
Component updates for Laravel 5.5 : Mail

### ISSUE THREAD

**Issue by jonathanbossenger** [mattstauffer/Torch#82]
Complete update of the [Mail](https://github.com/mattstauffer/Torch/tree/master/4.2/mail) Component to Laravel 5.5 

See #73 for full details of this task/requirements.

**Comment by OwenMelbz** [comment]
Ah just happened to need this today :D

Found https://github.com/hazzardweb/mail but its out dated, need to figure out how to patch it up
