### ISSUE TITLE
How use Queued Event Listeners

### ISSUE THREAD

**Issue by tobidsn** [mattstauffer/Torch#92]
Hi mattstauffer, 
how to use Queued Event Listeners with redis ?

in laravel 

```
<?php

namespace App\Listeners;

use App\Events\OrderShipped;
use Illuminate\Contracts\Queue\ShouldQueue;

class SendShipmentNotification implements ShouldQueue
{
    //
}

```
https://laravel.com/docs/5.5/events#queued-event-listeners

how to use other than in laravel?

**Comment by mattstauffer** [comment]
Sorry for the delay. Please re open if still a problem with modern dependencies and code.
