### ISSUE TITLE
Add scheduling, console file, and any other missing Artisan tooling

### ISSUE THREAD

**Issue by mattstauffer** [mattstauffer/Torch#94]
Just merged #91 which gets us basic Artisan but likely needs some additional work.

**Comment by jreason** [comment]
@mattstauffer i know you are upgrading to 5.5 at the moment, but to have Scheduling with multi server support which was introduced in 5.6 would be awesome!

```
$schedule->command('report:generate')
                ->fridays()
                ->at('17:00')
                ->onOneServer();
```

**Comment by Gummibeer** [comment]
The schedule was added in #178 as requested in #41
