### ISSUE TITLE
Error with Pagination

### ISSUE THREAD

**Issue by mkraha** [mattstauffer/Torch#95]
Always` getting error with pagination if i used links() or render();
```Fatal error: Uncaught Error: Call to a member function make() on null in \vendor\illuminate\pagination\Paginator.php:127```

Here is code:
```
$allItems = DB::table('products);
$allProductsCount = get_allItems()::get()->count();
$currentPage  = isset($_GET['page']) ? (int) $_GET['page'] : 1;
$perPage      = 10;
$currentItems = array_slice($allItems, $perPage * ($currentPage - 1), $perPage);
$paginator = new Illuminate\Pagination\Paginator($allItems, 10, $currentPage);
echo $paginator->links();
```

**Comment by mattstauffer** [comment]
Sorry for the delay. Please re open if still a problem with modern dependencies and code.
