### ISSUE TITLE
Laravel 5.4 Queue

### ISSUE THREAD

**Issue by jan-obtam** [mattstauffer/Torch#96]
Hi!

I just want to ask, is it possible to use Laravel 5.4 Queue component in a standalone application? I need it to be 5.4 because the target project still uses PHP 5.6 and there's no upgrade in sight in the near future.

**Comment by mattstauffer** [comment]
Probably? Try this branch out and see if it works for you :)

https://github.com/mattstauffer/Torch/tree/queue/components/queue

This is on 5.1, but it was never fully tested after it was pulled in from 4.2, so it may just not work. But take a look and see!

**Comment by itelmenko** [comment]
I think it is not good idea to use an http-server for queue worker daemon.
How can I run queue daemon in background? Must I use artisan command with 
```
$worker->daemon('redis', 'default', $options);
```
?

**Comment by atefBB** [comment]
@itelmenko I have the same issue as yours, how did you solve it?!

**Comment by itelmenko** [comment]
I did not resolve it, sorry
